### PR TITLE
Throw error when badly formatted changelog

### LINKED ISSUE #6: Fails when separator used at end of file

### PR DESCRIPTION
**Pull request by adrienDog**
Fixes #6 

And add the check to the verify task

### CODE REVIEW

**Review by lapostoj — APPROVED** [review]
For me looks good but might be biased since I reported it 😅

File: bin/parser/index.js [hunk 1]
```diff
@@ -15,9 +15,28 @@ function parseChangelogItem(item) {
   };
 }
 
+function isUsableItem(potentialItem) {
+  return potentialItem.split('\n').length > 1;
+}
+
+function isChangelogCorrectlyFormatted(items) {
```
Comment (oliverviljamaa) [inline bin/parser/index.js]: Any issues with replacing this with `return items.every(isUsableItem)`? Not sure whether it is lazy or not, but the readability would be way worth it anyway imo.

File: bin/parser/index.js [hunk 2]
```diff
@@ -15,9 +15,28 @@ function parseChangelogItem(item) {
...
+formatted. Please check you have no trailing separator at the end of your CHANGELOG`;
+function checkChangelogIsCorrectlyFormatted(items) {
+  if (!isChangelogCorrectlyFormatted(items)) throw new Error(BADLY_FORMATTED_CHANGELOG);
+}
+
 function parseChangelog(stdOut) {
   const changelogItems = stdOut.split(SEPARATOR);
-  return changelogItems.map(parseChangelogItem);
+  checkChangelogIsCorrectlyFormatted(changelogItems);
+  return changelogItems.filter(isUsableItem).map(parseChangelogItem);
```
Comment (oliverviljamaa) [inline bin/parser/index.js]: Is the `filter` necessary? Aren't we already throwing when any item is not usable in the check on the previous line?

**Review by Tankenstein — APPROVED** [review]

**Review by oliverviljamaa — APPROVED** [review]
